# fly.toml app configuration file generated for withered-sky-7506 on 2023-08-07T15:48:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "withered-sky-7506"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="inventory_images"
  destination="/app/public/images"
